// ============================================================
//  Стенд фальсифікації пакета 47 (с62): №23 `schema_digest` (0185).
//
//  Головне питання стенда: чи ловлять піни САМЕ ті способи послабити гілку,
//  кожен з яких лишає SQL на вигляд робочим —
//    • сортувати колонки по тексту замість `attnum` (тоді `drop column note`
//      + `add column note text` дає ТОЙ САМИЙ дайджест при знищених даних);
//    • оголосити гілку enum і забути додати її в `cur` (мітки не стережуться,
//      а на вигляд усе на місці — рівно та діра, яку знайшло ревʼю);
//    • прибрати виняток `conindid` (індекси, що підпирають constraint, почнуть
//      червонити ДВІ гілки на одну правку);
//    • прибрати identity з рядка колонки (`set generated by default` на
//      `audit_log.id` тихо пускає клієнта підставляти свій id в аудит);
//    • звузити `relkind` назад до ('r','v') — matview і секційна таблиця
//      зникають мовчки;
//    • сортувати мітки enum по алфавіту замість `enumsortorder`
//      (`add value ... before` стає невидимим);
//    • прибрати ключ із `expd` або зламати сортування ключів;
//    • перевести обробник винятку на `then null` — зламана перевірка стає
//      ЗЕЛЕНОЮ (клас боргу «fn_audit глотає БУДЬ-ЯКУ помилку»);
//    • послабити пост-асерт міграції: checked, асерт предстану, сигнатура.
//
//  ⚠️ Кожна мутація править ОБИДВА файли — фрагмент і міграцію — синхронно.
//     Інакше червонів би ще й пін «фрагмент є дослівною частиною міграції», і
//     адресність втрачалась би: мутація падала б із двох причин одразу.
//  ⚠️ Правлю БОЙОВІ файли → try/finally + відновлення на сигналах.
//  ⚠️ Кожен якір перевіряється на УНІКАЛЬНІСТЬ у КОЖНОМУ файлі.
//  ⚠️ Базова лінія мусить бути ЗЕЛЕНОЮ.
//
//  Запуск: node scripts/falsify-0185.mjs   Звіт: falsify-0185.md
// ============================================================
import { readFileSync, writeFileSync, existsSync, unlinkSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { verdictOf, finishStand } from "./lib/falsify-verdict.mjs";

const FILES = {
  mig: "supabase/migrations/0185_schema_digest.sql",
  frag: "scripts/frag/0185_check23.sql",
  tool: "scripts/print-schema-digest.mjs",
};
const SPECS = ["tests/schemaDigest.test.ts"];
const OUT = "falsify-0185.md";
const REPORT = ".falsify-0185.json";
const EXPECTED_RED = 12;

/** Правка, що йде і у фрагмент, і в міграцію (текст там дослівно однаковий). */
const both = (from, to) => [
  { file: "frag", from, to },
  { file: "mig", from, to },
];

const MUTATIONS = [
  {
    id: "A1", green: false, expect: /сортуються по attnum/,
    what: "колонки сортуються по тексту, а не по attnum (drop+add колонки стає невидимим)",
    edits: both("string_agg(line, ',' order by attnum)", "string_agg(line, ',' order by line)"),
  },
  {
    id: "A2", green: false, expect: /cur склеює РІВНО чотири джерела/,
    what: "гілку enum оголошено, але прибрано з `cur` (мітки не стережуться)",
    edits: both("    union all select key, dig from enu\n", ""),
  },
  {
    id: "A3", green: false, expect: /ВИКЛЮЧАЄ ті, що підпирають constraint/,
    what: "знято виняток conindid — одна правка червонить дві гілки",
    edits: both(
      "       and not exists (select 1 from pg_constraint c\n                        where c.conindid = i.indexrelid)",
      ""),
  },
  {
    id: "A4", green: false, expect: /несе тип, NOT NULL, DEFAULT, identity/,
    what: "прибрано identity з рядка колонки (set generated by default тихне)",
    edits: both(
      "             || case when a.attidentity::text = '' then ''\n                     else '#' || a.attidentity::text end\n",
      ""),
  },
  {
    id: "A5", green: false, expect: /охоплені relkind/,
    what: "relkind звужено назад до ('r','v') — matview і секція зникають",
    edits: both("c.relkind in ('r', 'v', 'm', 'p', 'f')", "c.relkind in ('r', 'v')"),
  },
  {
    id: "A6", green: false, expect: /сортує мітки по enumsortorder/,
    what: "мітки enum сортуються по алфавіту (add value ... before невидиме)",
    edits: both("order by e.enumsortorder", "order by e.enumlabel"),
  },
  {
    id: "A7", green: false, expect: /рівно 84 ключі/,
    what: "прибрано один ключ із expd (таблиця перестає стерегтись)",
    edits: both("      ('t:rate_limits','3:e56d35f7a3c2'),\n", ""),
  },
  {
    id: "A8", green: false, expect: /ключі відсортовані/,
    what: "порядок ключів у expd зламано — наступний передрук дасть шумний diff",
    edits: both(
      "      ('e:call_status','5:3435f2ba4c42'),\n      ('e:case_status','3:2b4224315c0f'),",
      "      ('e:case_status','3:2b4224315c0f'),\n      ('e:call_status','5:3435f2ba4c42'),"),
  },
  {
    id: "A9", green: false, expect: /НЕ глотає помилку/,
    what: "обробник винятку переведено на `then null` — зламана перевірка ЗЕЛЕНА",
    edits: both(
      "  /* 0174 */ exception when others then\n  /* 0174 */   v_fail := v_fail || jsonb_build_array(jsonb_build_object(\n  /* 0174 */     'check', 'schema_digest', 'offenders',\n  /* 0174 */     to_jsonb(array['raised:' || sqlstate || ':' || left(sqlerrm, 120)])));",
      "  /* 0174 */ exception when others then null;\n  /* 0174 */ begin"),
  },
  {
    id: "B1", file: "mig", green: false, expect: /checked = 23/,
    what: "пост-асерт лишили на checked = 22 — гілку могли не вставити зовсім",
    from: "if (v ->> 'checked')::int <> 23 then", to: "if (v ->> 'checked')::int <> 22 then",
  },
  {
    id: "B2", file: "mig", green: false, expect: /передрук наосліп заборонено/,
    what: "знято асерт предстану — 0185 затерла б ручну правку прода мовчки",
    from: "     is distinct from '11a297318da068f53b113c3d9120e6b8' then\n    raise exception '0185: тіло сторожа в проді НЕ дорівнює 0184 — передрук наосліп заборонено';\n  end if;\n",
    to: "     is distinct from 'x' then null; end if;\n",
  },
  {
    id: "B3", file: "mig", green: false, expect: /звужено сигнатурою/,
    what: "знято фільтр по сигнатурі — перегрузка зробила б асерт брехливим",
    from: "         and pg_get_function_identity_arguments(p.oid) = 'p_write boolean')",
    to: "         )",
  },

  /* ── РЕФАКТОРНІ КОНТРОЛІ: мусять лишитись ЗЕЛЕНИМИ ──
     Без них зелений стенд не відрізнити від стенда, що червоніє на будь-що. */
  {
    id: "R1", green: true, expect: /./,
    what: "рефакторний: правка коментаря всередині гілки",
    edits: both("--     ПʼЯТЬ ГІЛОК, один список offenders", "--     ПʼЯТЬ ГІЛОК (рефактор-контроль), один список offenders"),
  },
  {
    id: "R2", file: "tool", green: true, expect: /./,
    what: "рефакторний: правка коментаря в приладі (гілки не чіпає)",
    from: "//  Запуск:", to: "//  ЗАПУСК:",
  },
];

/* ── ІНВЕНТАР: кожен якір мусить існувати рівно один раз у СВОЄМУ файлі ── */
{
  let bad = 0;
  for (const m of MUTATIONS) {
    const eds = m.edits ?? [{ file: m.file, from: m.from, to: m.to }];
    for (const e of eds) {
      const src = readFileSync(FILES[e.file], "utf8");
      const n = src.split(e.from).length - 1;
      if (n !== 1) {
        console.error(`⛔ ІНВЕНТАР БРЕШЕ: ${m.id} у ${FILES[e.file]} — якір трапляється ${n} раз(ів).`);
        bad++;
      }
    }
  }
  if (bad) { console.error("Стенд НЕ прогнано."); process.exit(1); }
}

const orig = {};
for (const [k, p] of Object.entries(FILES)) orig[k] = readFileSync(p, "utf8");
let restored = false;
function restore() {
  if (restored) return;
  restored = true;
  for (const [k, p] of Object.entries(FILES)) writeFileSync(p, orig[k]);
}
process.on("SIGINT", () => { restore(); process.exit(130); });
process.on("SIGTERM", () => { restore(); process.exit(143); });
process.on("uncaughtException", (e) => { restore(); console.error(e); process.exit(2); });

function run() {
  if (existsSync(REPORT)) unlinkSync(REPORT);
  spawnSync("npx", ["vitest", "run", ...SPECS, "--reporter=json", `--outputFile.json=${REPORT}`],
    { shell: true, stdio: "ignore" });
  if (!existsSync(REPORT)) return { crashed: true, ok: false, red: [], all: [] };
  let r;
  try { r = JSON.parse(readFileSync(REPORT, "utf8")); }
  catch { return { crashed: true, ok: false, red: [], all: [] }; }
  const red = [], all = [];
  for (const f of r.testResults || []) {
    for (const a of f.assertionResults || []) {
      const n = a.fullName || a.title;
      all.push(n);
      if (a.status !== "passed") red.push(n);
    }
  }
  return { crashed: false, ok: r.success === true && red.length === 0, red, all, total: r.numTotalTests };
}

const lines = [];
let addressedOk = 0;
try {
  const base = run();
  lines.push(`# Стенд фальсифікації пакета 47 — №23 schema_digest (0185)\n`);
  lines.push(`**БАЗОВА ЛІНІЯ:** ${base.ok ? "ЗЕЛЕНА" : "ЧЕРВОНА"} (${base.total} тестів)\n`);
  if (!base.ok) {
    lines.push(`\n⛔ Базова лінія червона — стенд НІЧОГО не доводить. Червоні: ${base.red.join(", ")}\n`);
  } else {
    lines.push(`\n| # | мутація | очікування | факт | вердикт |`);
    lines.push(`|---|---|---|---|---|`);
    for (const m of MUTATIONS) {
      const eds = (m.edits ?? [{ file: m.file, from: m.from, to: m.to }])
        .map((e) => ({ ...e, path: FILES[e.file], src: readFileSync(FILES[e.file], "utf8") }));
      const cur = {};
      for (const e of eds) {
        const base2 = cur[e.path] ?? e.src;
        cur[e.path] = base2.replace(e.from, () => e.to);
      }
      for (const [p, txt] of Object.entries(cur)) writeFileSync(p, txt);
      const res = run();
      for (const e of eds) writeFileSync(e.path, e.src);
      const wantRed = !m.green;
      if (res.crashed) {
        lines.push(`| ${m.id} | ${m.what} | ${wantRed ? "ЧЕРВОНЕ" : "ЗЕЛЕНЕ"} | прогін не відбувся | ⛔ мутація зламала збірку |`);
        continue;
      }
      const gotRed = !res.ok;
      const fact = gotRed ? res.red.map((t) => `«${t}»`).join("; ") : "усе зелене";
      const missed = wantRed && gotRed && !res.red.some((t) => m.expect.test(t));
      const noSuchGuard = missed && !res.all.some((t) => m.expect.test(t));
      const verdict = noSuchGuard ? "⛔ СТОРОЖА З ТАКИМ ІМЕНЕМ НЕМАЄ (дефект стенда)"
        : missed ? "⛔ ЧУЖИЙ спек"
        : (wantRed === gotRed ? "✅" : "⛔ ПІН НЕ ТРИМАЄ");
      if (verdict === "✅" && wantRed) addressedOk++;
      const want = wantRed ? `ЧЕРВОНЕ: ${m.expect.source}` : "ЗЕЛЕНЕ";
      lines.push(`| ${m.id} | ${m.what} | ${want} | ${fact} | ${verdict} |`);
    }
  }
} finally {
  restore();
  if (existsSync(REPORT)) unlinkSync(REPORT);
  const verdict = verdictOf(lines, MUTATIONS.length);
  lines.push(`\n${verdict.summary}`);
  lines.push(`\n## ПІДСУМОК: ${addressedOk}/${EXPECTED_RED} адресних, ${MUTATIONS.length - EXPECTED_RED} рефакторних`);
  writeFileSync(OUT, lines.join("\n") + "\n");
  console.log(lines.join("\n"));
  console.log(`\nЗвіт: ${OUT}. Файли відновлено.`);
  finishStand({
    ok: !(!verdict.ok) && addressedOk === EXPECTED_RED,
    red: "\n⛔ ВЕРДИКТ: СТЕНД ЧЕРВОНИЙ — причина в таблиці вище.",
  });
}
